# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170303_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='votes',
        ),
        migrations.AddField(
            model_name='photo',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Не нравится'),
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Нравится'),
        ),
    ]
